# --- DEPLOYMENT (GIỮ NGUYÊN) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-frontend
  template:
    metadata:
      labels:
        app: banking-frontend
    spec:
      containers:
      - name: frontend
        image: acesme/bank-frontend:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 80

---

# --- SERVICE (SỬA PHẦN NÀY) ---
apiVersion: v1
kind: Service
metadata:
  name: banking-frontend-svc
spec:
  type: ClusterIP 
  selector:
    app: banking-frontend
  ports:
    - port: 80         # Người dùng vào bằng cổng 80 (http://...)
      targetPort: 80   # Chuyển vào container cổng 80